# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file FantasyBasketball/pom.xml

    - name: Run fantasyGameTests
      run: cd FantasyBasketball && mvn -Dtest=fantasyGameTests test 

    - name: Run fantasyLeagueTests
      run: cd FantasyBasketball && mvn -Dtest=fantasyLeagueTests test 
      
    - name: Run fantasyPlayerTests
      run: cd FantasyBasketball && mvn -Dtest=fantasyPlayerTests test
      
    - name: Run fantasyStatsTests
      run: cd FantasyBasketball && mvn -Dtest=fantasyStatsTests test
      
    - name: Run fantasyTeamTests
      run: cd FantasyBasketball && mvn -Dtest=fantasyTeamTests test
      
    - name: Run userTests
      run: cd FantasyBasketball && mvn -Dtest=userTests test
      
    - name: Run fantasyLeagueUtilityTests
      run: cd FantasyBasketball && mvn -Dtest=fantasyLeagueUtilityTests test 
      
    - name: Run fantasyStatsUtilityTests
      run: cd FantasyBasketball && mvn -Dtest=fantasyStatsUtilityTests test
      
    - name: Run RoundRobinSchedulerTests
      run: cd FantasyBasketball && mvn -Dtest=RoundRobinSchedulerTests test 
      
    - name: Export test results
      run: cp FantasyBasketball/target/surefire-reports/*.txt UnitTesting
    
